# Generated by Django 3.2.10 on 2022-05-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_screenshot',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
    ]
