# Generated by Django 3.2.10 on 2022-05-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0003_project_project_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_screenshot',
            field=models.ImageField(default='photo/default.jpg', upload_to='photo/'),
        ),
    ]
